sudo: required
env:
  global:
     - CODECOV_TOKEN=:9f8267a5-1057-4165-8176-a9320f2841f8

services:
  - docker

before_install:
  - pip install --user codecov
  - pip install --user coverage

language: scala

scala:
  - 2.12.8

jdk:
  - openjdk8
  - openjdk11
  
before_script:
  - export FLAGS="--coverage "
  - export CXXFLAGS="--coverage "
  - export LDFLAGS="--coverage "
script:
  - cd ~
  - make
  - make test
  - sbt clean coverage test coverageReport && sbt coverageAggregate

after_success:
  - codecov -t 9f8267a5-1057-4165-8176-a9320f2841f8
